---
- :name: __jdc
  :value: '122270672'
  :path: "/"
  :domain: ".jd.com"
  :expires: 
  :secure: false
- :name: __jdv
  :value: 122270672|direct|-|none|-|1499764669838
  :path: "/"
  :domain: ".jd.com"
  :expires: !ruby/object:DateTime 2017-07-26 09:17:49.000000006 Z
  :secure: false
- :name: o2-webp
  :value: 'false'
  :path: "/"
  :domain: ".www.jd.com"
  :expires: !ruby/object:DateTime 2017-08-10 09:17:49.000000006 Z
  :secure: false
- :name: TrackID
  :value: 139biRL8nAM9JupqirfzhLe04DSPEEDki6fYyYpIiOv_9Lmrlbeb7TDY1_CFRC3cetU4aJu-Qs0LLZOmvXwzvmQdsfn5Vv7ur5cfU-8Ce3rLIQl8kVxi34T5_b-Gc2WqQ
  :path: "/"
  :domain: ".jd.com"
  :expires: !ruby/object:DateTime 2022-07-10 09:19:41.000000099 Z
  :secure: false
- :name: pinId
  :value: wqVCzR6OpOKcQo6_WUln7Q
  :path: "/"
  :domain: ".jd.com"
  :expires: !ruby/object:DateTime 2018-07-11 09:19:41.000000099 Z
  :secure: false
- :name: pin
  :value: dongpeng0803
  :path: "/"
  :domain: ".jd.com"
  :expires: !ruby/object:DateTime 2017-08-10 09:19:41.000000099 Z
  :secure: false
- :name: unick
  :value: MaratSafin
  :path: "/"
  :domain: ".jd.com"
  :expires: !ruby/object:DateTime 2017-08-10 09:19:41.000000099 Z
  :secure: false
- :name: thor
  :value: A972D667AD5582862B36E5AB30B7B48AB5DA4E3BD76BE4FB6EA9D67571B35734636AE260BC355E576BBE674C1BCD8F59A051E35F987C40D0E64119DCE414C3CC3840B32582EEC6E2D4F8E069C22635BCA011F7DE259F9893C25E1551D1903CB32314C23862CC7F7D53DD11930AF69A6F19499FE2BA25BA7E3C30E07ACC73ADB8E4E66C3FA6BE19CA07A2F87D13EFFD69
  :path: "/"
  :domain: ".jd.com"
  :expires: 
  :secure: false
- :name: _tp
  :value: iFmIhZ7Vrvd7oEGiv6MwoQ%3D%3D
  :path: "/"
  :domain: ".jd.com"
  :expires: !ruby/object:DateTime 2017-08-10 09:19:41.000000099 Z
  :secure: false
- :name: _pst
  :value: dongpeng0803
  :path: "/"
  :domain: ".jd.com"
  :expires: !ruby/object:DateTime 2017-08-10 09:19:41.000000099 Z
  :secure: false
- :name: ceshi3.com
  :value: '201'
  :path: "/"
  :domain: ".jd.com"
  :expires: 
  :secure: false
- :name: __jda
  :value: 122270672.1499764669838910891666.1499764670.1499764670.1499764670.1
  :path: "/"
  :domain: ".jd.com"
  :expires: !ruby/object:DateTime 2018-01-07 09:20:09.999999963 Z
  :secure: false
- :name: __jdb
  :value: 122270672.5.1499764669838910891666|1.1499764670
  :path: "/"
  :domain: ".jd.com"
  :expires: !ruby/object:DateTime 2017-07-11 09:50:09.999999858 Z
  :secure: false
- :name: __jdu
  :value: '1499764669838910891666'
  :path: "/"
  :domain: ".jd.com"
  :expires: !ruby/object:DateTime 2018-01-07 09:20:09.999999963 Z
  :secure: false
